"""Centralized constants and tunables for the backend."""

# WebSocket stream loop
WS_TICK_INTERVAL_SECONDS = 1.0
SNAPSHOT_INTERVAL_SECONDS = 60
TRAIL_CHECK_INTERVAL_SECONDS = 5
WS_RECONNECT_FAILURE_THRESHOLD = 3

# MT5
MT5_INIT_RETRIES = 3

# Trading
DEFAULT_ORDER_DEVIATION = 20
DEFAULT_MAGIC = 234000
